openapi: 3.0.0
info:
  title: Insitution
  version: 1.0.0
  description: >
    Insitution API for Lenz Core.
  tags:
    - name: Institution
      description: Insitution API for Lenz Core.

paths:
  /api/v1/institutions:
    get:
      summary: List Institutions
      tags:
        - Institution
      responses:
        '200':
          description: OK