# yaml-language-server: \$schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: institution
generate:
  chi-server: true
  models: true
  strict-server: true
  embedded-spec: true
output: institution.gen.go

output-options:
  skip-prune: true
  nullable-type: true
import-mapping:
  ../common/schema.yaml: github.com/lenz-core/packages/shared/schema