// Package corebanking provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package corebanking

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for APIAccountNormalBalance.
const (
	APIAccountNormalBalanceCredit APIAccountNormalBalance = "credit"
	APIAccountNormalBalanceDebit  APIAccountNormalBalance = "debit"
)

// Defines values for APIJournalEntryEntryType.
const (
	APIJournalEntryEntryTypeInbound  APIJournalEntryEntryType = "inbound"
	APIJournalEntryEntryTypeOutbound APIJournalEntryEntryType = "outbound"
	APIJournalEntryEntryTypeReversal APIJournalEntryEntryType = "reversal"
)

// Defines values for APIPostingDirection.
const (
	APIPostingDirectionCredit APIPostingDirection = "credit"
	APIPostingDirectionDebit  APIPostingDirection = "debit"
)

// Defines values for APITransactionDirection.
const (
	APITransactionDirectionInbound  APITransactionDirection = "inbound"
	APITransactionDirectionOutbound APITransactionDirection = "outbound"
	APITransactionDirectionReversal APITransactionDirection = "reversal"
)

// Defines values for APITransactionStatus.
const (
	APITransactionStatusFailed    APITransactionStatus = "failed"
	APITransactionStatusPending   APITransactionStatus = "pending"
	APITransactionStatusSucceeded APITransactionStatus = "succeeded"
)

// Defines values for APITransferDirection.
const (
	APITransferDirectionInbound  APITransferDirection = "inbound"
	APITransferDirectionOutbound APITransferDirection = "outbound"
	APITransferDirectionReversal APITransferDirection = "reversal"
)

// Defines values for APITransferLedgerStatus.
const (
	APITransferLedgerStatusNoPosting       APITransferLedgerStatus = "no_posting"
	APITransferLedgerStatusPending         APITransferLedgerStatus = "pending"
	APITransferLedgerStatusPosted          APITransferLedgerStatus = "posted"
	APITransferLedgerStatusReversalDeficit APITransferLedgerStatus = "reversal_deficit"
)

// Defines values for APITransferProviderStatus.
const (
	APITransferProviderStatusFailed    APITransferProviderStatus = "failed"
	APITransferProviderStatusPending   APITransferProviderStatus = "pending"
	APITransferProviderStatusSucceeded APITransferProviderStatus = "succeeded"
)

// Defines values for APITransferReconciliationStatus.
const (
	APITransferReconciliationStatusManualReview APITransferReconciliationStatus = "manual_review"
	APITransferReconciliationStatusMatched      APITransferReconciliationStatus = "matched"
	APITransferReconciliationStatusNoAction     APITransferReconciliationStatus = "no_action"
	APITransferReconciliationStatusPending      APITransferReconciliationStatus = "pending"
)

// Defines values for APITransferStatus.
const (
	APITransferStatusFailed    APITransferStatus = "failed"
	APITransferStatusPending   APITransferStatus = "pending"
	APITransferStatusSucceeded APITransferStatus = "succeeded"
)

// Defines values for MockTransferRequestScenario.
const (
	MockTransferRequestScenarioDelayed   MockTransferRequestScenario = "delayed"
	MockTransferRequestScenarioDuplicate MockTransferRequestScenario = "duplicate"
	MockTransferRequestScenarioFailed    MockTransferRequestScenario = "failed"
	MockTransferRequestScenarioPending   MockTransferRequestScenario = "pending"
	MockTransferRequestScenarioReversal  MockTransferRequestScenario = "reversal"
	MockTransferRequestScenarioSuccess   MockTransferRequestScenario = "success"
)

// Defines values for MockTransferRequestStatus.
const (
	MockTransferRequestStatusFailed    MockTransferRequestStatus = "failed"
	MockTransferRequestStatusPending   MockTransferRequestStatus = "pending"
	MockTransferRequestStatusSucceeded MockTransferRequestStatus = "succeeded"
)

// APIAccount defines model for APIAccount.
type APIAccount struct {
	AccountNumber        string                                `json:"account_number"`
	AllowNegativeBalance bool                                  `json:"allow_negative_balance"`
	CreatedAt            time.Time                             `json:"created_at"`
	CurrencyId           string                                `json:"currency_id"`
	CustomerId           nullable.Nullable[openapi_types.UUID] `json:"customer_id,omitempty"`
	Id                   openapi_types.UUID                    `json:"id"`
	InstitutionId        openapi_types.UUID                    `json:"institution_id"`
	Kind                 string                                `json:"kind"`
	Name                 string                                `json:"name"`
	NormalBalance        APIAccountNormalBalance               `json:"normal_balance"`
	ProductType          string                                `json:"product_type"`
	Status               string                                `json:"status"`
	UpdatedAt            time.Time                             `json:"updated_at"`
}

// APIAccountNormalBalance defines model for APIAccount.NormalBalance.
type APIAccountNormalBalance string

// APIAccountBalance defines model for APIAccountBalance.
type APIAccountBalance struct {
	AccountId          openapi_types.UUID                    `json:"account_id"`
	AvailableMinor     int64                                 `json:"available_minor"`
	CurrencyId         string                                `json:"currency_id"`
	InstitutionId      openapi_types.UUID                    `json:"institution_id"`
	LastJournalEntryId nullable.Nullable[openapi_types.UUID] `json:"last_journal_entry_id,omitempty"`
	LedgerMinor        int64                                 `json:"ledger_minor"`
	UpdatedAt          time.Time                             `json:"updated_at"`
}

// APIBranch defines model for APIBranch.
type APIBranch struct {
	Code          string             `json:"code"`
	CreatedAt     time.Time          `json:"created_at"`
	Id            openapi_types.UUID `json:"id"`
	InstitutionId openapi_types.UUID `json:"institution_id"`
	Name          string             `json:"name"`
	Status        string             `json:"status"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

// APICustomer defines model for APICustomer.
type APICustomer struct {
	BranchId      openapi_types.UUID `json:"branch_id"`
	CreatedAt     time.Time          `json:"created_at"`
	Email         string             `json:"email"`
	FirstName     string             `json:"first_name"`
	Id            openapi_types.UUID `json:"id"`
	InstitutionId openapi_types.UUID `json:"institution_id"`
	LastName      string             `json:"last_name"`
	Phone         string             `json:"phone"`
	Status        string             `json:"status"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

// APIInstitution defines model for APIInstitution.
type APIInstitution struct {
	Code       string             `json:"code"`
	CreatedAt  time.Time          `json:"created_at"`
	CurrencyId string             `json:"currency_id"`
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`
	ShortName  string             `json:"short_name"`
	Status     string             `json:"status"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

// APIJournalEntry defines model for APIJournalEntry.
type APIJournalEntry struct {
	CreatedAt        time.Time                             `json:"created_at"`
	CurrencyId       string                                `json:"currency_id"`
	EntryType        APIJournalEntryEntryType              `json:"entry_type"`
	Id               openapi_types.UUID                    `json:"id"`
	InstitutionId    openapi_types.UUID                    `json:"institution_id"`
	Narration        string                                `json:"narration"`
	TotalCreditMinor int64                                 `json:"total_credit_minor"`
	TotalDebitMinor  int64                                 `json:"total_debit_minor"`
	TransferId       nullable.Nullable[openapi_types.UUID] `json:"transfer_id,omitempty"`
}

// APIJournalEntryEntryType defines model for APIJournalEntry.EntryType.
type APIJournalEntryEntryType string

// APIJournalWithPostings defines model for APIJournalWithPostings.
type APIJournalWithPostings struct {
	Balanced     bool            `json:"balanced"`
	JournalEntry APIJournalEntry `json:"journal_entry"`
	Postings     []APIPosting    `json:"postings"`
}

// APIPosting defines model for APIPosting.
type APIPosting struct {
	AccountId      openapi_types.UUID  `json:"account_id"`
	AmountMinor    int64               `json:"amount_minor"`
	CreatedAt      time.Time           `json:"created_at"`
	CurrencyId     string              `json:"currency_id"`
	Direction      APIPostingDirection `json:"direction"`
	Id             openapi_types.UUID  `json:"id"`
	InstitutionId  openapi_types.UUID  `json:"institution_id"`
	JournalEntryId openapi_types.UUID  `json:"journal_entry_id"`
}

// APIPostingDirection defines model for APIPosting.Direction.
type APIPostingDirection string

// APISeedResult defines model for APISeedResult.
type APISeedResult struct {
	Account         APIAccount     `json:"account"`
	Branch          APIBranch      `json:"branch"`
	ClearingAccount APIAccount     `json:"clearing_account"`
	Customer        APICustomer    `json:"customer"`
	Institution     APIInstitution `json:"institution"`
}

// APITransaction defines model for APITransaction.
type APITransaction struct {
	AccountId      openapi_types.UUID                    `json:"account_id"`
	AmountMinor    int64                                 `json:"amount_minor"`
	CreatedAt      time.Time                             `json:"created_at"`
	CurrencyId     string                                `json:"currency_id"`
	Direction      APITransactionDirection               `json:"direction"`
	Id             string                                `json:"id"`
	JournalEntryId nullable.Nullable[openapi_types.UUID] `json:"journal_entry_id,omitempty"`
	Narration      string                                `json:"narration"`
	SignedMinor    int64                                 `json:"signed_minor"`
	Status         APITransactionStatus                  `json:"status"`
	TransferId     openapi_types.UUID                    `json:"transfer_id"`
}

// APITransactionDirection defines model for APITransaction.Direction.
type APITransactionDirection string

// APITransactionStatus defines model for APITransaction.Status.
type APITransactionStatus string

// APITransfer defines model for APITransfer.
type APITransfer struct {
	AccountId            openapi_types.UUID                    `json:"account_id"`
	AmountMinor          int64                                 `json:"amount_minor"`
	CreatedAt            time.Time                             `json:"created_at"`
	CurrencyId           string                                `json:"currency_id"`
	Direction            APITransferDirection                  `json:"direction"`
	FailureReason        nullable.Nullable[string]             `json:"failure_reason,omitempty"`
	Id                   openapi_types.UUID                    `json:"id"`
	IdempotencyKey       string                                `json:"idempotency_key"`
	InstitutionId        openapi_types.UUID                    `json:"institution_id"`
	JournalEntryId       nullable.Nullable[openapi_types.UUID] `json:"journal_entry_id,omitempty"`
	LedgerStatus         APITransferLedgerStatus               `json:"ledger_status"`
	Narration            string                                `json:"narration"`
	Provider             string                                `json:"provider"`
	ProviderEventId      nullable.Nullable[string]             `json:"provider_event_id,omitempty"`
	ProviderReference    string                                `json:"provider_reference"`
	ProviderStatus       APITransferProviderStatus             `json:"provider_status"`
	ReconciliationStatus APITransferReconciliationStatus       `json:"reconciliation_status"`
	ReversalOfTransferId nullable.Nullable[openapi_types.UUID] `json:"reversal_of_transfer_id,omitempty"`
	Status               APITransferStatus                     `json:"status"`
	UpdatedAt            time.Time                             `json:"updated_at"`
}

// APITransferDirection defines model for APITransfer.Direction.
type APITransferDirection string

// APITransferLedgerStatus defines model for APITransfer.LedgerStatus.
type APITransferLedgerStatus string

// APITransferProviderStatus defines model for APITransfer.ProviderStatus.
type APITransferProviderStatus string

// APITransferReconciliationStatus defines model for APITransfer.ReconciliationStatus.
type APITransferReconciliationStatus string

// APITransferStatus defines model for APITransfer.Status.
type APITransferStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// MockTransferRequest defines model for MockTransferRequest.
type MockTransferRequest struct {
	AccountId         openapi_types.UUID           `json:"account_id"`
	AmountMinor       int64                        `json:"amount_minor"`
	CurrencyId        *string                      `json:"currency_id,omitempty"`
	DelaySeconds      *int64                       `json:"delay_seconds,omitempty"`
	IdempotencyKey    *string                      `json:"idempotency_key,omitempty"`
	InstitutionId     *openapi_types.UUID          `json:"institution_id,omitempty"`
	Narration         *string                      `json:"narration,omitempty"`
	ProviderEventId   *string                      `json:"provider_event_id,omitempty"`
	ProviderReference *string                      `json:"provider_reference,omitempty"`
	Scenario          *MockTransferRequestScenario `json:"scenario,omitempty"`
	Status            *MockTransferRequestStatus   `json:"status,omitempty"`
}

// MockTransferRequestScenario defines model for MockTransferRequest.Scenario.
type MockTransferRequestScenario string

// MockTransferRequestStatus defines model for MockTransferRequest.Status.
type MockTransferRequestStatus string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// InstitutionID defines model for InstitutionID.
type InstitutionID = openapi_types.UUID

// Error defines model for Error.
type Error = ErrorResponse

// GetAccountBalanceParams defines parameters for GetAccountBalance.
type GetAccountBalanceParams struct {
	XInstitutionID InstitutionID `json:"X-Institution-ID"`
}

// ListAccountTransactionsParams defines parameters for ListAccountTransactions.
type ListAccountTransactionsParams struct {
	XInstitutionID InstitutionID `json:"X-Institution-ID"`
}

// GetJournalParams defines parameters for GetJournal.
type GetJournalParams struct {
	XInstitutionID InstitutionID `json:"X-Institution-ID"`
}

// ListTransfersParams defines parameters for ListTransfers.
type ListTransfersParams struct {
	XInstitutionID InstitutionID `json:"X-Institution-ID"`
}

// ListCustomerAccountsParams defines parameters for ListCustomerAccounts.
type ListCustomerAccountsParams struct {
	XInstitutionID InstitutionID `json:"X-Institution-ID"`
}

// MockInboundTransferParams defines parameters for MockInboundTransfer.
type MockInboundTransferParams struct {
	XInstitutionID InstitutionID  `json:"X-Institution-ID"`
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// MockOutboundTransferParams defines parameters for MockOutboundTransfer.
type MockOutboundTransferParams struct {
	XInstitutionID InstitutionID  `json:"X-Institution-ID"`
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetTransferParams defines parameters for GetTransfer.
type GetTransferParams struct {
	XInstitutionID InstitutionID `json:"X-Institution-ID"`
}

// ReverseTransferParams defines parameters for ReverseTransfer.
type ReverseTransferParams struct {
	XInstitutionID InstitutionID  `json:"X-Institution-ID"`
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// MockInboundTransferJSONRequestBody defines body for MockInboundTransfer for application/json ContentType.
type MockInboundTransferJSONRequestBody = MockTransferRequest

// MockOutboundTransferJSONRequestBody defines body for MockOutboundTransfer for application/json ContentType.
type MockOutboundTransferJSONRequestBody = MockTransferRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get account ledger and available balances
	// (GET /api/v1/accounts/{account_id}/balance)
	GetAccountBalance(w http.ResponseWriter, r *http.Request, accountId openapi_types.UUID, params GetAccountBalanceParams)
	// List ledger-backed account transactions
	// (GET /api/v1/accounts/{account_id}/transactions)
	ListAccountTransactions(w http.ResponseWriter, r *http.Request, accountId openapi_types.UUID, params ListAccountTransactionsParams)
	// Inspect a journal entry and postings
	// (GET /api/v1/admin/ledger/journal/{journal_entry_id})
	GetJournal(w http.ResponseWriter, r *http.Request, journalEntryId openapi_types.UUID, params GetJournalParams)
	// List recent institution transfers
	// (GET /api/v1/admin/transfers)
	ListTransfers(w http.ResponseWriter, r *http.Request, params ListTransfersParams)
	// List accounts owned by a customer inside an institution
	// (GET /api/v1/customers/{customer_id}/accounts)
	ListCustomerAccounts(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID, params ListCustomerAccountsParams)
	// Seed demo transaction-spine data
	// (POST /api/v1/demo/seed)
	SeedDemo(w http.ResponseWriter, r *http.Request)
	// Record a mock inbound provider transfer event
	// (POST /api/v1/transfers/mock/inbound)
	MockInboundTransfer(w http.ResponseWriter, r *http.Request, params MockInboundTransferParams)
	// Initiate a mock outbound provider transfer
	// (POST /api/v1/transfers/mock/outbound)
	MockOutboundTransfer(w http.ResponseWriter, r *http.Request, params MockOutboundTransferParams)
	// Get a transfer by ID
	// (GET /api/v1/transfers/{transfer_id})
	GetTransfer(w http.ResponseWriter, r *http.Request, transferId openapi_types.UUID, params GetTransferParams)
	// Reverse a succeeded transfer as a new ledger event
	// (POST /api/v1/transfers/{transfer_id}/reverse)
	ReverseTransfer(w http.ResponseWriter, r *http.Request, transferId openapi_types.UUID, params ReverseTransferParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get account ledger and available balances
// (GET /api/v1/accounts/{account_id}/balance)
func (_ Unimplemented) GetAccountBalance(w http.ResponseWriter, r *http.Request, accountId openapi_types.UUID, params GetAccountBalanceParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List ledger-backed account transactions
// (GET /api/v1/accounts/{account_id}/transactions)
func (_ Unimplemented) ListAccountTransactions(w http.ResponseWriter, r *http.Request, accountId openapi_types.UUID, params ListAccountTransactionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Inspect a journal entry and postings
// (GET /api/v1/admin/ledger/journal/{journal_entry_id})
func (_ Unimplemented) GetJournal(w http.ResponseWriter, r *http.Request, journalEntryId openapi_types.UUID, params GetJournalParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List recent institution transfers
// (GET /api/v1/admin/transfers)
func (_ Unimplemented) ListTransfers(w http.ResponseWriter, r *http.Request, params ListTransfersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List accounts owned by a customer inside an institution
// (GET /api/v1/customers/{customer_id}/accounts)
func (_ Unimplemented) ListCustomerAccounts(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID, params ListCustomerAccountsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Seed demo transaction-spine data
// (POST /api/v1/demo/seed)
func (_ Unimplemented) SeedDemo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Record a mock inbound provider transfer event
// (POST /api/v1/transfers/mock/inbound)
func (_ Unimplemented) MockInboundTransfer(w http.ResponseWriter, r *http.Request, params MockInboundTransferParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Initiate a mock outbound provider transfer
// (POST /api/v1/transfers/mock/outbound)
func (_ Unimplemented) MockOutboundTransfer(w http.ResponseWriter, r *http.Request, params MockOutboundTransferParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a transfer by ID
// (GET /api/v1/transfers/{transfer_id})
func (_ Unimplemented) GetTransfer(w http.ResponseWriter, r *http.Request, transferId openapi_types.UUID, params GetTransferParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reverse a succeeded transfer as a new ledger event
// (POST /api/v1/transfers/{transfer_id}/reverse)
func (_ Unimplemented) ReverseTransfer(w http.ResponseWriter, r *http.Request, transferId openapi_types.UUID, params ReverseTransferParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAccountBalance operation middleware
func (siw *ServerInterfaceWrapper) GetAccountBalance(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "account_id" -------------
	var accountId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", chi.URLParam(r, "account_id"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "account_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAccountBalanceParams

	headers := r.Header

	// ------------- Required header parameter "X-Institution-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Institution-ID")]; found {
		var XInstitutionID InstitutionID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Institution-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Institution-ID", valueList[0], &XInstitutionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Institution-ID", Err: err})
			return
		}

		params.XInstitutionID = XInstitutionID

	} else {
		err := fmt.Errorf("Header parameter X-Institution-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Institution-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccountBalance(w, r, accountId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAccountTransactions operation middleware
func (siw *ServerInterfaceWrapper) ListAccountTransactions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "account_id" -------------
	var accountId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", chi.URLParam(r, "account_id"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "account_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAccountTransactionsParams

	headers := r.Header

	// ------------- Required header parameter "X-Institution-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Institution-ID")]; found {
		var XInstitutionID InstitutionID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Institution-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Institution-ID", valueList[0], &XInstitutionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Institution-ID", Err: err})
			return
		}

		params.XInstitutionID = XInstitutionID

	} else {
		err := fmt.Errorf("Header parameter X-Institution-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Institution-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccountTransactions(w, r, accountId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJournal operation middleware
func (siw *ServerInterfaceWrapper) GetJournal(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "journal_entry_id" -------------
	var journalEntryId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "journal_entry_id", chi.URLParam(r, "journal_entry_id"), &journalEntryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "journal_entry_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetJournalParams

	headers := r.Header

	// ------------- Required header parameter "X-Institution-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Institution-ID")]; found {
		var XInstitutionID InstitutionID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Institution-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Institution-ID", valueList[0], &XInstitutionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Institution-ID", Err: err})
			return
		}

		params.XInstitutionID = XInstitutionID

	} else {
		err := fmt.Errorf("Header parameter X-Institution-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Institution-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJournal(w, r, journalEntryId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTransfers operation middleware
func (siw *ServerInterfaceWrapper) ListTransfers(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTransfersParams

	headers := r.Header

	// ------------- Required header parameter "X-Institution-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Institution-ID")]; found {
		var XInstitutionID InstitutionID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Institution-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Institution-ID", valueList[0], &XInstitutionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Institution-ID", Err: err})
			return
		}

		params.XInstitutionID = XInstitutionID

	} else {
		err := fmt.Errorf("Header parameter X-Institution-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Institution-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTransfers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCustomerAccounts operation middleware
func (siw *ServerInterfaceWrapper) ListCustomerAccounts(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "customer_id" -------------
	var customerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "customer_id", chi.URLParam(r, "customer_id"), &customerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "customer_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCustomerAccountsParams

	headers := r.Header

	// ------------- Required header parameter "X-Institution-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Institution-ID")]; found {
		var XInstitutionID InstitutionID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Institution-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Institution-ID", valueList[0], &XInstitutionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Institution-ID", Err: err})
			return
		}

		params.XInstitutionID = XInstitutionID

	} else {
		err := fmt.Errorf("Header parameter X-Institution-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Institution-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCustomerAccounts(w, r, customerId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SeedDemo operation middleware
func (siw *ServerInterfaceWrapper) SeedDemo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SeedDemo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MockInboundTransfer operation middleware
func (siw *ServerInterfaceWrapper) MockInboundTransfer(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params MockInboundTransferParams

	headers := r.Header

	// ------------- Required header parameter "X-Institution-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Institution-ID")]; found {
		var XInstitutionID InstitutionID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Institution-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Institution-ID", valueList[0], &XInstitutionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Institution-ID", Err: err})
			return
		}

		params.XInstitutionID = XInstitutionID

	} else {
		err := fmt.Errorf("Header parameter X-Institution-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Institution-ID", Err: err})
		return
	}

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MockInboundTransfer(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MockOutboundTransfer operation middleware
func (siw *ServerInterfaceWrapper) MockOutboundTransfer(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params MockOutboundTransferParams

	headers := r.Header

	// ------------- Required header parameter "X-Institution-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Institution-ID")]; found {
		var XInstitutionID InstitutionID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Institution-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Institution-ID", valueList[0], &XInstitutionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Institution-ID", Err: err})
			return
		}

		params.XInstitutionID = XInstitutionID

	} else {
		err := fmt.Errorf("Header parameter X-Institution-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Institution-ID", Err: err})
		return
	}

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MockOutboundTransfer(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTransfer operation middleware
func (siw *ServerInterfaceWrapper) GetTransfer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "transfer_id" -------------
	var transferId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "transfer_id", chi.URLParam(r, "transfer_id"), &transferId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transfer_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTransferParams

	headers := r.Header

	// ------------- Required header parameter "X-Institution-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Institution-ID")]; found {
		var XInstitutionID InstitutionID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Institution-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Institution-ID", valueList[0], &XInstitutionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Institution-ID", Err: err})
			return
		}

		params.XInstitutionID = XInstitutionID

	} else {
		err := fmt.Errorf("Header parameter X-Institution-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Institution-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTransfer(w, r, transferId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReverseTransfer operation middleware
func (siw *ServerInterfaceWrapper) ReverseTransfer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "transfer_id" -------------
	var transferId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "transfer_id", chi.URLParam(r, "transfer_id"), &transferId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transfer_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ReverseTransferParams

	headers := r.Header

	// ------------- Required header parameter "X-Institution-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Institution-ID")]; found {
		var XInstitutionID InstitutionID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Institution-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Institution-ID", valueList[0], &XInstitutionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Institution-ID", Err: err})
			return
		}

		params.XInstitutionID = XInstitutionID

	} else {
		err := fmt.Errorf("Header parameter X-Institution-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Institution-ID", Err: err})
		return
	}

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReverseTransfer(w, r, transferId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/accounts/{account_id}/balance", wrapper.GetAccountBalance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/accounts/{account_id}/transactions", wrapper.ListAccountTransactions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/ledger/journal/{journal_entry_id}", wrapper.GetJournal)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/transfers", wrapper.ListTransfers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/customers/{customer_id}/accounts", wrapper.ListCustomerAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/demo/seed", wrapper.SeedDemo)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/transfers/mock/inbound", wrapper.MockInboundTransfer)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/transfers/mock/outbound", wrapper.MockOutboundTransfer)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/transfers/{transfer_id}", wrapper.GetTransfer)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/transfers/{transfer_id}/reverse", wrapper.ReverseTransfer)
	})

	return r
}

type ErrorJSONResponse ErrorResponse

type GetAccountBalanceRequestObject struct {
	AccountId openapi_types.UUID `json:"account_id"`
	Params    GetAccountBalanceParams
}

type GetAccountBalanceResponseObject interface {
	VisitGetAccountBalanceResponse(w http.ResponseWriter) error
}

type GetAccountBalance200JSONResponse APIAccountBalance

func (response GetAccountBalance200JSONResponse) VisitGetAccountBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAccountBalance400JSONResponse struct{ ErrorJSONResponse }

func (response GetAccountBalance400JSONResponse) VisitGetAccountBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAccountBalance404JSONResponse ErrorResponse

func (response GetAccountBalance404JSONResponse) VisitGetAccountBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListAccountTransactionsRequestObject struct {
	AccountId openapi_types.UUID `json:"account_id"`
	Params    ListAccountTransactionsParams
}

type ListAccountTransactionsResponseObject interface {
	VisitListAccountTransactionsResponse(w http.ResponseWriter) error
}

type ListAccountTransactions200JSONResponse []APITransaction

func (response ListAccountTransactions200JSONResponse) VisitListAccountTransactionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListAccountTransactions400JSONResponse struct{ ErrorJSONResponse }

func (response ListAccountTransactions400JSONResponse) VisitListAccountTransactionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetJournalRequestObject struct {
	JournalEntryId openapi_types.UUID `json:"journal_entry_id"`
	Params         GetJournalParams
}

type GetJournalResponseObject interface {
	VisitGetJournalResponse(w http.ResponseWriter) error
}

type GetJournal200JSONResponse APIJournalWithPostings

func (response GetJournal200JSONResponse) VisitGetJournalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetJournal400JSONResponse struct{ ErrorJSONResponse }

func (response GetJournal400JSONResponse) VisitGetJournalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetJournal404JSONResponse ErrorResponse

func (response GetJournal404JSONResponse) VisitGetJournalResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListTransfersRequestObject struct {
	Params ListTransfersParams
}

type ListTransfersResponseObject interface {
	VisitListTransfersResponse(w http.ResponseWriter) error
}

type ListTransfers200JSONResponse []APITransfer

func (response ListTransfers200JSONResponse) VisitListTransfersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListTransfers400JSONResponse struct{ ErrorJSONResponse }

func (response ListTransfers400JSONResponse) VisitListTransfersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListCustomerAccountsRequestObject struct {
	CustomerId openapi_types.UUID `json:"customer_id"`
	Params     ListCustomerAccountsParams
}

type ListCustomerAccountsResponseObject interface {
	VisitListCustomerAccountsResponse(w http.ResponseWriter) error
}

type ListCustomerAccounts200JSONResponse []APIAccount

func (response ListCustomerAccounts200JSONResponse) VisitListCustomerAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListCustomerAccounts400JSONResponse struct{ ErrorJSONResponse }

func (response ListCustomerAccounts400JSONResponse) VisitListCustomerAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SeedDemoRequestObject struct {
}

type SeedDemoResponseObject interface {
	VisitSeedDemoResponse(w http.ResponseWriter) error
}

type SeedDemo200JSONResponse APISeedResult

func (response SeedDemo200JSONResponse) VisitSeedDemoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SeedDemo404JSONResponse struct{ ErrorJSONResponse }

func (response SeedDemo404JSONResponse) VisitSeedDemoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type MockInboundTransferRequestObject struct {
	Params MockInboundTransferParams
	Body   *MockInboundTransferJSONRequestBody
}

type MockInboundTransferResponseObject interface {
	VisitMockInboundTransferResponse(w http.ResponseWriter) error
}

type MockInboundTransfer200JSONResponse APITransfer

func (response MockInboundTransfer200JSONResponse) VisitMockInboundTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type MockInboundTransfer400JSONResponse struct{ ErrorJSONResponse }

func (response MockInboundTransfer400JSONResponse) VisitMockInboundTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type MockInboundTransfer409JSONResponse ErrorResponse

func (response MockInboundTransfer409JSONResponse) VisitMockInboundTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type MockInboundTransfer422JSONResponse ErrorResponse

func (response MockInboundTransfer422JSONResponse) VisitMockInboundTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type MockOutboundTransferRequestObject struct {
	Params MockOutboundTransferParams
	Body   *MockOutboundTransferJSONRequestBody
}

type MockOutboundTransferResponseObject interface {
	VisitMockOutboundTransferResponse(w http.ResponseWriter) error
}

type MockOutboundTransfer200JSONResponse APITransfer

func (response MockOutboundTransfer200JSONResponse) VisitMockOutboundTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type MockOutboundTransfer400JSONResponse struct{ ErrorJSONResponse }

func (response MockOutboundTransfer400JSONResponse) VisitMockOutboundTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type MockOutboundTransfer409JSONResponse ErrorResponse

func (response MockOutboundTransfer409JSONResponse) VisitMockOutboundTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type MockOutboundTransfer422JSONResponse ErrorResponse

func (response MockOutboundTransfer422JSONResponse) VisitMockOutboundTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type GetTransferRequestObject struct {
	TransferId openapi_types.UUID `json:"transfer_id"`
	Params     GetTransferParams
}

type GetTransferResponseObject interface {
	VisitGetTransferResponse(w http.ResponseWriter) error
}

type GetTransfer200JSONResponse APITransfer

func (response GetTransfer200JSONResponse) VisitGetTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTransfer400JSONResponse struct{ ErrorJSONResponse }

func (response GetTransfer400JSONResponse) VisitGetTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetTransfer404JSONResponse ErrorResponse

func (response GetTransfer404JSONResponse) VisitGetTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ReverseTransferRequestObject struct {
	TransferId openapi_types.UUID `json:"transfer_id"`
	Params     ReverseTransferParams
}

type ReverseTransferResponseObject interface {
	VisitReverseTransferResponse(w http.ResponseWriter) error
}

type ReverseTransfer200JSONResponse APITransfer

func (response ReverseTransfer200JSONResponse) VisitReverseTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ReverseTransfer400JSONResponse struct{ ErrorJSONResponse }

func (response ReverseTransfer400JSONResponse) VisitReverseTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ReverseTransfer404JSONResponse ErrorResponse

func (response ReverseTransfer404JSONResponse) VisitReverseTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ReverseTransfer409JSONResponse ErrorResponse

func (response ReverseTransfer409JSONResponse) VisitReverseTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get account ledger and available balances
	// (GET /api/v1/accounts/{account_id}/balance)
	GetAccountBalance(ctx context.Context, request GetAccountBalanceRequestObject) (GetAccountBalanceResponseObject, error)
	// List ledger-backed account transactions
	// (GET /api/v1/accounts/{account_id}/transactions)
	ListAccountTransactions(ctx context.Context, request ListAccountTransactionsRequestObject) (ListAccountTransactionsResponseObject, error)
	// Inspect a journal entry and postings
	// (GET /api/v1/admin/ledger/journal/{journal_entry_id})
	GetJournal(ctx context.Context, request GetJournalRequestObject) (GetJournalResponseObject, error)
	// List recent institution transfers
	// (GET /api/v1/admin/transfers)
	ListTransfers(ctx context.Context, request ListTransfersRequestObject) (ListTransfersResponseObject, error)
	// List accounts owned by a customer inside an institution
	// (GET /api/v1/customers/{customer_id}/accounts)
	ListCustomerAccounts(ctx context.Context, request ListCustomerAccountsRequestObject) (ListCustomerAccountsResponseObject, error)
	// Seed demo transaction-spine data
	// (POST /api/v1/demo/seed)
	SeedDemo(ctx context.Context, request SeedDemoRequestObject) (SeedDemoResponseObject, error)
	// Record a mock inbound provider transfer event
	// (POST /api/v1/transfers/mock/inbound)
	MockInboundTransfer(ctx context.Context, request MockInboundTransferRequestObject) (MockInboundTransferResponseObject, error)
	// Initiate a mock outbound provider transfer
	// (POST /api/v1/transfers/mock/outbound)
	MockOutboundTransfer(ctx context.Context, request MockOutboundTransferRequestObject) (MockOutboundTransferResponseObject, error)
	// Get a transfer by ID
	// (GET /api/v1/transfers/{transfer_id})
	GetTransfer(ctx context.Context, request GetTransferRequestObject) (GetTransferResponseObject, error)
	// Reverse a succeeded transfer as a new ledger event
	// (POST /api/v1/transfers/{transfer_id}/reverse)
	ReverseTransfer(ctx context.Context, request ReverseTransferRequestObject) (ReverseTransferResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetAccountBalance operation middleware
func (sh *strictHandler) GetAccountBalance(w http.ResponseWriter, r *http.Request, accountId openapi_types.UUID, params GetAccountBalanceParams) {
	var request GetAccountBalanceRequestObject

	request.AccountId = accountId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccountBalance(ctx, request.(GetAccountBalanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccountBalance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAccountBalanceResponseObject); ok {
		if err := validResponse.VisitGetAccountBalanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAccountTransactions operation middleware
func (sh *strictHandler) ListAccountTransactions(w http.ResponseWriter, r *http.Request, accountId openapi_types.UUID, params ListAccountTransactionsParams) {
	var request ListAccountTransactionsRequestObject

	request.AccountId = accountId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAccountTransactions(ctx, request.(ListAccountTransactionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAccountTransactions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAccountTransactionsResponseObject); ok {
		if err := validResponse.VisitListAccountTransactionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJournal operation middleware
func (sh *strictHandler) GetJournal(w http.ResponseWriter, r *http.Request, journalEntryId openapi_types.UUID, params GetJournalParams) {
	var request GetJournalRequestObject

	request.JournalEntryId = journalEntryId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJournal(ctx, request.(GetJournalRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJournal")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJournalResponseObject); ok {
		if err := validResponse.VisitGetJournalResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTransfers operation middleware
func (sh *strictHandler) ListTransfers(w http.ResponseWriter, r *http.Request, params ListTransfersParams) {
	var request ListTransfersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTransfers(ctx, request.(ListTransfersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTransfers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTransfersResponseObject); ok {
		if err := validResponse.VisitListTransfersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCustomerAccounts operation middleware
func (sh *strictHandler) ListCustomerAccounts(w http.ResponseWriter, r *http.Request, customerId openapi_types.UUID, params ListCustomerAccountsParams) {
	var request ListCustomerAccountsRequestObject

	request.CustomerId = customerId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCustomerAccounts(ctx, request.(ListCustomerAccountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCustomerAccounts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCustomerAccountsResponseObject); ok {
		if err := validResponse.VisitListCustomerAccountsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SeedDemo operation middleware
func (sh *strictHandler) SeedDemo(w http.ResponseWriter, r *http.Request) {
	var request SeedDemoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SeedDemo(ctx, request.(SeedDemoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SeedDemo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SeedDemoResponseObject); ok {
		if err := validResponse.VisitSeedDemoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// MockInboundTransfer operation middleware
func (sh *strictHandler) MockInboundTransfer(w http.ResponseWriter, r *http.Request, params MockInboundTransferParams) {
	var request MockInboundTransferRequestObject

	request.Params = params

	var body MockInboundTransferJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.MockInboundTransfer(ctx, request.(MockInboundTransferRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MockInboundTransfer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MockInboundTransferResponseObject); ok {
		if err := validResponse.VisitMockInboundTransferResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// MockOutboundTransfer operation middleware
func (sh *strictHandler) MockOutboundTransfer(w http.ResponseWriter, r *http.Request, params MockOutboundTransferParams) {
	var request MockOutboundTransferRequestObject

	request.Params = params

	var body MockOutboundTransferJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.MockOutboundTransfer(ctx, request.(MockOutboundTransferRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MockOutboundTransfer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MockOutboundTransferResponseObject); ok {
		if err := validResponse.VisitMockOutboundTransferResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTransfer operation middleware
func (sh *strictHandler) GetTransfer(w http.ResponseWriter, r *http.Request, transferId openapi_types.UUID, params GetTransferParams) {
	var request GetTransferRequestObject

	request.TransferId = transferId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTransfer(ctx, request.(GetTransferRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTransfer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTransferResponseObject); ok {
		if err := validResponse.VisitGetTransferResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReverseTransfer operation middleware
func (sh *strictHandler) ReverseTransfer(w http.ResponseWriter, r *http.Request, transferId openapi_types.UUID, params ReverseTransferParams) {
	var request ReverseTransferRequestObject

	request.TransferId = transferId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReverseTransfer(ctx, request.(ReverseTransferRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReverseTransfer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReverseTransferResponseObject); ok {
		if err := validResponse.VisitReverseTransferResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbW2/cuBX+KwTbR9njXFC085ZsFttp013Da6AF0kDgiGdmGEuklqTsTo357wVJUaLu",
	"c3XSYF8C2+Ll8Dvf+Xh4yDzjRGS54MC1wvNnnBNJMtAg7W8LClkuNPBk+3fYmr8wjud4A4SCxBHmJAM8",
	"D5tdmXYRlvBbwSRQPNeygAirZAMZMQNk5D8fga/1Bs9fvf5zhDPGq98jrLe5GVBpyfga73YRXnClmS40",
	"E3zxYdCCf10F7a4WH0ZNWAmZEY3nuCgYxVMm7MxQKhdcgcXkRymFND8kgmvg2vxI8jxlCTGTz74owc3f",
	"6vn+KGGF5/gPsxrqmfuqZna0u3J8NxsFlUiWm8Hw3E2HvAXXFpOysxn73e3iXZKIwtmRS5GD1MxZStyH",
	"mBfZEqzJrbVFmKSpeIo5rIlmjxAvSUp4AkHTpRApEG7aJhKIBhoT3QCREg1XmmWAo+74SSGloUXMaMv5",
	"bxq4v+ntq7TIQJZ9217jRZqSZQrev53+/d26zWrixHt2eWCc9sLp2Nj3wQyZhvgCLzI8/4QpLJnGFl3K",
	"NP7cM10uBS0SHbsPPaMrTXShej8VOT3QabswdD5hi0ALo6hNrXLlJTItiwdZ1qRHB6RqXQ3qNZZUoyWW",
	"XyDRZsV1RLyv0e4PjD3dTR4Js1SLM8Zd7Fd9GNd/elt3YlzDGuSp1D+CkylROv4iCslJGgPXcnts3KRA",
	"1yAPWuvJLAs80se2lgNaNrZ5NE2Q95LwZNMlRiJof4Qdo32X059BmXl5IbCIVeF/bMD+UEp91yNL66l9",
	"gTnGTZARlvZCtmJS6XgQ7Mv518by4Lz5RvBvxf21expwhUvwCHvDj2dJkOJdOHRP0u5TY3gj5Ij3L+5j",
	"H8q1GVWUN2X2WDf+zW1SP5o9qsePp7urG+J2O/Tpk8+8GF+KwqYrotD+RwmPIBVJexOxSyq6lMQTu/NV",
	"C03S2GWIB+3LrqNNMQ/rJwlXq2NT772UI/BJJw+swOhbQS8cDRKO8+6fTG9uhdKMr1XPfuNyRtp/BGrk",
	"V1NHuzbVjXQH8zINmdpjjNJW6xZnkIFn24G5aVswV1QvagAZP8XJiXJmWw8zLWOcZSb6XvVmzBcIfcok",
	"JD6wDjhzXS7U98nRjwmozrhRM6uukWg5qh1+05H0KwC9A1Wkw0WHPYjt6xY7n0bs0adM3I3jUyAGnfio",
	"CZMg4ZzoVeWmTXfv0TPMVzo+DL5V6w/sqpyHe5Y64JZ7o9ok6c+Pzh3KXzF8j924jwrFyePy+Nat2JoD",
	"PQjHOsPzC86BUzNehFWRJAAUbL5NWNrQ9CBhGN+/95CXcIQRIalywJaiNJY9tr9Pi819acl3sDsddI44",
	"E/UNSwoJsQRSFqbPVjitq/7xg7sdGK2kX2y33LeiNRZYJlsCV4SMy8wpQDamsGLJQKowLgC5FI+MOvpO",
	"wOObxvAIFa0nF1f1krACwzYYtSM+g7xISARPWMrsskdHzIhONh5Y4mUjI7wgaSzhkcHTwBQl8mIVn3Ya",
	"OYugXriMPqyrbbe1yTzkjIkcrx27AU97GTUo2pMH/uYFV0fDM1CKrGEyOlpw+m59M/5DJA9+07iD3wpQ",
	"7o6OUmbsJ+ltYMGKpAqir7uxNDcJCitiM2v8808/21g5ZNOAlGxjZShB1bgtN322vIim7yeYDRU8VvVU",
	"ApxIJsLgtyGvbHBVMlCGfoRp4W5yDeUtmDC5w9byUrsulJUjRWfshqTBuG4M7KxfVsLZFN4m/5IDf3e7",
	"QEoUMgG0EhLpDSBHQY0+Av8v+kFIQLo+S1ypnHFAf72/v0WqkCuSwDW63wDKRPKAgNNcMK4VIhIQhUxc",
	"CZ5uEeEUScgI42ht9AEttyi4JkeJ4Cu2vv63LfIwbeQb19Obf5aEPzi8DPjO/lfXN9c3BnSRAyc5w3P8",
	"xv4pwjnRG+uFGcnZ7PHVrERMzZ5r7Haz4Ap2DVYYTORbmxYUz/FPoFvXh1HjUcSn/mNf3WTWfLGwi8on",
	"C8a++sFCw537P1Voc+Rz63HC65ubsz1N6F6k9jxPKFugEtZr45u3zoi+sStj3cMH1/rt3q1NtBVZRuTW",
	"eQqVMCK3KVrSVZeF3iYT6Zqsje9wyKvPZrhxsgRRoAYZ85EpT5n7sP33zJt9i5dhSaJbwBxkU4A72jCl",
	"hdwezKwGV4yPSpJcLUnyALSijm76bJopNGN85saalceT2XP7nLIbE5iyLHwZhvTUAb9ZfekryffQomyG",
	"7JLQE9Mb5KvbLyk4C65ySDQi6EvDIKM6QbV9Twb5U824sNxXrU4ky4tG/Kq8RpoI9ztIwEegWeMZYly6",
	"IYOstB5+H9/4AqyaPQfvz3bV/jDqLF8qfucbXyTAw3dx/w97QFB2nyKEB7De15nSZ2CF9x4ST7xMRZGH",
	"0XCFUUCEo2ZRfpIrJtmdKXCXhUYAuqz4FYB+gEzgy+pocCHTg6oxAFGiCTLGImkbXp8khWZCm+z3HBTM",
	"TPvAV8XlzBwkZr60OYilOdcvXKNKZE4PsKkOzRfQLmhsTeG9oNuz+bCvZrFrHgFNeO8uS6Nau7sk8t+M",
	"wgpJj9p3/3JI69evj6PmnbUPEXc8LVmFfL2g2g2QLS8cwdOq8D5K1F/KVr8z9XemDueTTDOiwXPVM6tL",
	"1sNo+hwUzEfPIWckZ0+e0rxC/GbPIJem0inVjVqtlltk/1fLsTSYuRImDKvWnWvw9QTru2XRXVk9rr35",
	"InQ6TMdae6jlAiKoKlXXxhOFCOLw5ItuExvprvry3F/tUVFVqYvqw1rkhy/P2iqy5+w651yBLBNOKQoN",
	"6rrmTGjB7vPufwEAAP//wooTSuQ2AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
